[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "Service"
url = "service/"
weight = 4
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "Service"
parent = "More"
url = "service/"
weight = 1
[[main]]
name = "Contact"
url = "contact/"
weight = 6
