address_descriptors = false
author = "Themefisher"
copyright = ""
custom_script = ""
description = "Blessings is a boutique with gifts and cosmetics for you and your home."
email = "demo@email.com"
favicon = "images/favicon.png"
google_tag_manager = ""
image = "images/Blessings-Logo.svg"
location = ""
logo = "images/Blessings-Logo.svg"
logo_text = "Blessings Logo"
logo_width = "200px"
navbar_fixed = false
phone = "254-445-3333"
recaptcha_site_key = "xxx-xxxxxxxxxxxxxxxxxxxxxxxx"
[baidu]
analytics_id = ""
enable = false
[contact.form]
action = "#"
enable = true
success_image = "images/paper-plane.svg"
use_netlify = true
use_recaptcha = true
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[matomo]
enable = false
id = ""
url = ""
[navigation_button]
enable = true
label = "get a quote"
link = "contact"
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = ""
[site_verification]
baidu = ""
bing = ""
google = ""
[widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/DublinTexasGifts/"
title = "facebook"
